'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { useApp } from '@/components/app-state';
import { APORTE_ATALHOS, CATEGORIAS, EVOLUCAO, FILA, FILTROS_INVEST } from '@/lib/demo-data';

function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) {
  return <div className="card-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2 className="h-display">{title}</h2></div>{action}</div>;
}

function Notice({ icon, title, text, tone = 'info' }: { icon: string; title: string; text: string; tone?: 'info' | 'warn' | 'ok' | 'err' }) {
  return <div className={`callout callout-${tone}`}><i className={`bi ${icon}`} aria-hidden="true" /><div><p className="callout-title">{title}</p><p className="small">{text}</p></div></div>;
}

export function DashboardPage() {
  const app = useApp();
  return <div className="stack-lg">
    <div className="row-between"><p className="note">Visão sintética do produto planejado. Nenhum dado financeiro real é utilizado.</p><div className="row-tight"><button className="btn btn-neutral btn-sm" onClick={app.toggleOffline}><i className="bi bi-wifi-off" />Alternar offline</button><button className="btn btn-neutral btn-sm" onClick={app.toggleSurvival}><i className="bi bi-shield-exclamation" />Modo de sobrevivência</button></div></div>
    <section className="grid grid-300">
      <article className="card card-lg"><p className="eyebrow">Saldo Livre de Risco</p><p className="metric metric-hero num">R$ 3.450,00</p><p className="small muted">R$ 8.412,60 em contas − R$ 4.962,60 comprometidos até 30 set.</p><Link className="btn btn-primary" href="/extratos/recorrencias">Entender o cálculo</Link></article>
      <article className="card"><p className="eyebrow">Média de gastos diária</p><p className="metric num">R$ 78,68</p><p className="small muted">Meta diária: R$ 100,00</p><div className="bar"><div className="bar-fill" style={{width:'79%'}} /></div><span className="chip chip-ok"><i className="bi bi-arrow-down" />21% abaixo da meta</span></article>
      <article className="card"><p className="eyebrow">Consumo do mês</p><p className="metric num">59%</p><p className="small muted">R$ 2.361,40 de R$ 4.000,00</p><div className="bar"><div className="bar-fill bar-fill-walnut" style={{width:'59%'}} /></div><p className="tiny muted">Restam 25 dias no período</p></article>
    </section>
    <section className="grid grid-320">
      <article className="card"><SectionTitle eyebrow="Hoje" title="Notificações ativas" action={<button className="btn btn-link" onClick={() => app.open('notif')}>Ver todas</button>} /><Notice icon="bi-credit-card" title="Fatura vence em 5 dias" text="Aurora Platinum · R$ 1.842,60" tone="warn" /><Notice icon="bi-check2-square" title="4 lançamentos pedem decisão" text="Revise a fila para manter o saldo confiável." /></article>
      <article className="card"><SectionTitle eyebrow="Carteira" title="Quatro pilares" /><div className="stack">{[['Ações','27,1%'],['Real Estate','23,4%'],['Caixa','32,0%'],['Internacional','17,5%']].map(([n,p])=><div className="row-between" key={n}><span>{n}</span><strong className="num">{p}</strong></div>)}</div><Link className="btn btn-neutral" href="/patrimonio">Ver patrimônio</Link></article>
      <article className="card"><SectionTitle eyebrow="Próxima ação" title="Fila de conciliação" /><p className="metric num">4</p><p className="small muted">itens aguardando sua confirmação</p><Link className="btn btn-primary" href="/conciliacao">Começar triagem</Link></article>
    </section>
    <section className="grid grid-340">
      <article className="card card-lg"><SectionTitle title="Evolução financeira" /><div className="chart" aria-label="Evolução sintética de gastos e aportes">{EVOLUCAO.map(m=><div className="chart-col" key={m.mes}><div className="chart-bars"><div style={{height:`${m.gasto}%`}} title={`Gastos: ${m.gastoFmt}`} /><div className="bar-fill" style={{height:`${m.aporte}%`}} title={`Aportes: ${m.aporteFmt}`} /></div><span className="chart-label">{m.mes}</span></div>)}</div></article>
      <article className="card"><SectionTitle title="Gastos por categoria" />{CATEGORIAS.map(c=><div key={c.nome} style={{marginBottom:12}}><div className="row-between small"><span>{c.nome}</span><span className="num">{c.valor} · {c.pct}%</span></div><div className="bar bar-xs"><div className="bar-fill" style={{width:`${c.bar}%`}} /></div></div>)}</article>
    </section>
  </div>;
}

const transactions = [
  ['Hoje','Mercado Primavera','Alimentação','− R$ 186,42'],['Hoje','PIX recebido · Estúdio Norte','Receita','+ R$ 2.400,00'],['4 set','Posto Horizonte','Transporte','− R$ 220,00'],['3 set','CLARO*NET SP','Moradia','− R$ 129,90'],['2 set','PG *MERCADOLIVRE','Compras','− R$ 248,70'],
];

export function StatementsPage() {
  const app=useApp(); const [query,setQuery]=useState(''); const [state,setState]=useState('cheio');
  const rows=transactions.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase()));
  return <div className="stack-lg"><section className="card"><SectionTitle eyebrow="Setembro de 2026" title="Lançamentos" action={<button className="btn btn-primary" onClick={app.openImport}><i className="bi bi-file-earmark-arrow-up" />Importar extrato</button>} /><div className="row"><label className="field" style={{flex:1}}>Buscar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Descrição, categoria ou valor" /></label><label className="field">Estado<select value={state} onChange={e=>setState(e.target.value)}><option value="cheio">Com dados</option><option value="vazio">Vazio</option><option value="carregando">Carregando</option><option value="erro">Erro</option></select></label></div></section>
    {state==='erro'?<Notice icon="bi-exclamation-triangle" title="Não foi possível abrir seus lançamentos" text="Tente novamente. Seus dados locais não foram alterados." tone="err"/>:state==='carregando'?<section className="card">{[1,2,3,4].map(i=><div className="skeleton-row" key={i}><div className="skeleton-bar" /></div>)}</section>:state==='vazio'||rows.length===0?<section className="card empty"><i className="bi bi-receipt" /><h2 className="h-display">{query?'Nenhum lançamento corresponde aos filtros':'Nenhum lançamento por aqui'}</h2><p>{query?'Limpe a busca para voltar a ver todos os itens.':'Importe um OFX ou PDF para começar.'}</p><button className="btn btn-primary" onClick={query?()=>setQuery(''):app.openImport}>{query?'Limpar filtros':'Importar primeiro extrato'}</button></section>:<section className="card card-flush scroll-x"><table className="grid-table"><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th className="right">Valor</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r[1]}${i}`}><td>{r[0]}</td><td><strong>{r[1]}</strong><span className="cell-sub">Conta corrente Aurora</span></td><td><span className="chip">{r[2]}</span></td><td className="right num">{r[3]}</td></tr>)}</tbody></table></section>}
  </div>;
}

export function CardsPage(){return <div className="stack-lg"><section className="grid grid-320">{[{n:'Aurora Platinum',bill:'R$ 1.842,60',fee:'R$ 45,00',benefit:'R$ 82,40',progress:74},{n:'Vega Livre',bill:'R$ 936,20',fee:'Sem anuidade',benefit:'R$ 9,36',progress:47}].map(c=><article className="card" key={c.n}><SectionTitle eyebrow="Cartão de crédito" title={c.n}/><p className="small muted">Fatura atual</p><p className="metric num">{c.bill}</p><div className="row-between small"><span>Anuidade</span><strong>{c.fee}</strong></div><div className="row-between small"><span>Benefícios estimados</span><strong className="num">{c.benefit}</strong></div><p className="small">Progresso para isenção</p><div className="bar"><div className="bar-fill" style={{width:`${c.progress}%`}} /></div><p className="tiny muted">{c.progress}% da faixa mensal</p><Link className="btn btn-neutral" href={`/extratos/cartoes/${c.n==='Aurora Platinum'?'aurora':'vega'}`}>Ver detalhes</Link></article>)}</section><section className="card"><SectionTitle title="Milhas, pontos e cashback"/><div className="grid grid-230"><div><p className="eyebrow">Pontos</p><p className="metric num">12.480</p></div><div><p className="eyebrow">Cashback no ano</p><p className="metric num">R$ 286,40</p></div><div><p className="eyebrow">Próxima expiração</p><p className="metric">18 nov.</p></div></div></section></div>}

export function RecurrencesPage(){const [paid,setPaid]=useState(false);return <div className="stack-lg"><Notice icon="bi-calculator" title="R$ 4.962,60 estão comprometidos" text="Esse total é descontado do saldo para calcular o Saldo Livre de Risco."/><section className="card card-flush scroll-x"><table className="grid-table"><thead><tr><th>Obrigação</th><th>Vencimento</th><th>Conta</th><th>Status</th><th className="right">Valor</th></tr></thead><tbody>{[['Fatura Aurora Platinum','10 set','Conta Aurora','Conferir','R$ 1.842,60'],['Aluguel','08 set','Conta Aurora','Agendado','R$ 2.100,00'],['Energia','12 set','Conta Aurora','Previsto','R$ 286,40'],['Internet','15 set','Conta Aurora','Débito automático','R$ 129,90']].map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td><span className="chip chip-warn">{r[3]}</span></td><td className="right num">{r[4]}</td></tr>)}</tbody></table></section><section className="card"><SectionTitle title="Conferência rápida"/><p>A fatura Aurora foi debitada corretamente?</p><button className={`btn ${paid?'btn-neutral':'btn-primary'}`} onClick={()=>setPaid(true)}>{paid?<><i className="bi bi-check2"/>Conferida</>:'Marcar como conferida'}</button></section></div>}

export function ReconciliationPage(){const [index,setIndex]=useState(0);const [done,setDone]=useState(false);const item=FILA[index];if(done)return <section className="card empty"><i className="bi bi-check2-circle"/><h2 className="h-display">Nada pendente de conciliação</h2><p>As decisões foram aplicadas aos dados sintéticos desta demonstração.</p><button className="btn btn-neutral" onClick={()=>{setIndex(0);setDone(false)}}>Reiniciar demonstração</button></section>;return <div className="grid grid-320"><section className="card card-lg"><p className="eyebrow">Item {index+1} de {FILA.length}</p><h2 className="h-display-lg">{item.desc}</h2><p className="muted">{item.meta}</p><p className="metric num">{item.valor}</p><Notice icon="bi-stars" title={`Sugestão: ${item.sugestao}`} text={item.razao}/><div className="row-tight"><button className="btn btn-primary" onClick={()=>index===FILA.length-1?setDone(true):setIndex(index+1)}><i className="bi bi-check2"/>Confirmar</button><button className="btn btn-neutral"><i className="bi bi-pencil"/>Mudar categoria</button></div></section><aside className="stack"><article className="card"><p className="eyebrow">Progresso da fila</p><p className="metric num">{index + 1}/{FILA.length}</p><div className="bar"><div className="bar-fill" style={{width:`${((index+1)/FILA.length)*100}%`}}/></div></article><article className="card"><SectionTitle title="Ajustes financeiros"/><p className="small muted">Registre juros, multa, desconto ou correção sem apagar o valor original.</p><button className="btn btn-neutral">Adicionar ajuste</button></article></aside></div>}

export function InvoiceCheckPage(){const [ok,setOk]=useState(false);return <div className="stack-lg"><section className="grid grid-320"><article className="card"><p className="eyebrow">Fatura</p><h2 className="h-display">Aurora Platinum</h2><p className="metric num">R$ 1.842,60</p><p className="small muted">Fechada em 3 set. · vence em 10 set.</p></article><article className="card"><p className="eyebrow">Débito no extrato</p><h2 className="h-display">Conta corrente</h2><p className="metric num">R$ 1.842,60</p><p className="small muted">Agendado para 10 set.</p></article></section><Notice icon="bi-check2-circle" title="Valores correspondem" text="Confira a data e confirme apenas depois que o débito aparecer no extrato." tone="ok"/><button className={`btn ${ok?'btn-neutral':'btn-primary'}`} onClick={()=>setOk(true)}>{ok?'Fatura conciliada':'Marcar como conciliada'}</button></div>}

const pillars=[['Ações','27,1%','Dentro da faixa',100],['Real Estate','23,4%','Dentro da faixa',86],['Caixa','32,0%','Acima da faixa',100],['Ativos internacionais','17,5%','Prioridade',65]];
export function PortfolioPage(){return <div className="stack-lg"><Notice icon="bi-info-circle" title="Organização, não recomendação" text="A metodologia ARCA é creditada a Thiago Nigro (Primo Rico). O Talentum não oferece recomendação individual de investimento."/><section className="card"><SectionTitle eyebrow="Carteira total · R$ 40.000,00" title="Distribuição por pilar" action={<Link className="btn btn-primary" href="/patrimonio/aportes">Simular aporte</Link>}/><div className="grid grid-260">{pillars.map(([n,p,s,w])=><article className="card card-sm" key={n}><div className="row-between"><strong>{n}</strong><span className={`chip ${s==='Prioridade'?'chip-warn':'chip-ok'}`}>{s}</span></div><p className="metric num">{p}</p><div className="pillar-track"><div className="pillar-band"/><div className={s==='Prioridade'?'pillar-fill pillar-fill-priority':'pillar-fill'} style={{width:`${w}%`}}/></div><p className="tiny muted">Faixa equilibrada: 22,5%–27,5%</p></article>)}</div></section><section className="card"><SectionTitle title="Superávit identificado"/><p className="metric num">R$ 400,00</p><p className="muted">Sugestão: R$ 200,00 para Viagem em dezembro e R$ 200,00 para Ativos internacionais.</p><button className="btn btn-primary">Revisar destinação</button></section></div>}

export function ContributionsPage(){const app=useApp();const [amount,setAmount]=useState('1.000,00');const result=useMemo(()=>amount?`Direcione R$ ${amount} para Ativos internacionais.`:'Informe um valor para simular.',[amount]);return <div className="grid grid-340"><section className="card card-lg"><SectionTitle title="Quanto você pretende aportar?"/><label className="field field-amount">Valor do novo aporte<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/></label><div className="row-tight">{APORTE_ATALHOS.map(v=><button className="chip-toggle" key={v} onClick={()=>setAmount(v.replace('R$ ',''))}>{v}</button>)}</div>{app.survival?<Notice icon="bi-shield-exclamation" title="Sugestão pausada" text="No modo de sobrevivência, a prioridade é quitar a dívida de maior custo." tone="warn"/>:<Notice icon="bi-arrow-down-right" title="Ativos internacionais · 17,5%" text={result} tone="ok"/>}<button className="btn btn-primary" disabled={app.survival}>Registrar aporte planejado</button></section><aside className="card"><p className="eyebrow">Como a conta é feita</p><ol className="small muted"><li>Calculamos a participação de cada pilar.</li><li>Comparamos com a meta de 25%.</li><li>Respeitamos a faixa de 22,5% a 27,5%.</li><li>Priorizamos dinheiro novo; nunca sugerimos venda.</li></ol></aside></div>}

export function GoalsPage(){return <div className="stack-lg"><div className="row-between"><p className="note">Metas transformam objetivos em contribuições mensais explicáveis.</p><button className="btn btn-primary">Criar meta</button></div><section className="grid grid-300">{[['viagem','Viagem em dezembro','R$ 3.600,00','72%','R$ 300/mês'],['reserva','Reserva de emergência','R$ 18.000,00','48%','R$ 750/mês'],['notebook','Troca do notebook','R$ 6.500,00','31%','R$ 450/mês']].map(g=><article className="card" key={g[0]}><p className="eyebrow">Objetivo</p><h2 className="h-display">{g[1]}</h2><p className="metric num">{g[3]}</p><div className="bar"><div className="bar-fill" style={{width:g[3]}}/></div><div className="row-between small"><span>Meta</span><strong className="num">{g[2]}</strong></div><p className="small muted">Plano atual: {g[4]}</p><Link className="btn btn-neutral" href={`/patrimonio/metas/${g[0]}`}>Ver progresso</Link></article>)}</section></div>}

const articles=[{id:'fundos-logistica',tag:'Minha carteira · XPML11',title:'Fundos imobiliários de logística anunciam calendário de proventos do trimestre',source:'Jornal Econômico',time:'Há 18 min · 4 min de leitura'},{id:'taxa-basica',tag:'Macro',title:'Comitê mantém a taxa básica e sinaliza cautela para os próximos meses',source:'Agência Mercado',time:'Há 1 h · 6 min de leitura'},{id:'varejo-resultados',tag:'Mercado Geral',title:'Setor de varejo divulga resultados acima do previsto pelo consenso',source:'Boletim Financeiro',time:'Há 2 h · 3 min de leitura'}];
export function InvestPage(){const app=useApp();const [filter,setFilter]=useState(FILTROS_INVEST[0]);return <div className="stack-lg">{app.offline&&<Notice icon="bi-wifi-off" title="Notícias indisponíveis offline" text="Seus dados financeiros continuam funcionando normalmente."/>}<div className="row-tight">{FILTROS_INVEST.map(f=><button key={f} className="chip-toggle" aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{articles.filter(a=>filter==='Mercado Geral'||a.tag.startsWith(filter)).map(a=><article className="card" key={a.id}><p className="eyebrow">{a.tag}</p><h2 className="h-display">{a.title}</h2><p className="small muted">{a.source} · {a.time}</p><p>Calendários e indicadores recentes ajudam a acompanhar o cenário, sem usar detalhes da sua carteira no processamento remoto.</p><div className="row-tight"><Link href={`/invest/${a.id}`} className="btn btn-primary">Resumir com IA</Link><a href="https://example.com" target="_blank" rel="noreferrer" className="btn btn-neutral"><i className="bi bi-box-arrow-up-right"/>Ler matéria original</a></div></article>)}</div>}

export function ArticlePage(){const [loading,setLoading]=useState(false);const run=()=>{setLoading(true);setTimeout(()=>setLoading(false),900)};return <article className="card card-lg"><p className="eyebrow">Resumo em tópicos · conteúdo público</p><h2 className="h-display-lg">Fundos imobiliários de logística anunciam calendário de proventos do trimestre</h2><p className="small muted">Fonte sintética: Jornal Econômico · 4 min de leitura</p><Notice icon="bi-stars" title="Resumo demonstrativo" text="O calendário concentra pagamentos no meio do mês; o setor mantém distribuição estável; datas devem ser verificadas na fonte original."/><ul><li>Pagamentos previstos para cotistas posicionados nas datas-base divulgadas.</li><li>Distribuições permanecem compatíveis com o trimestre anterior.</li><li>O conteúdo é informativo e não constitui recomendação.</li></ul><div className="row-tight"><button className="btn btn-primary" onClick={run} disabled={loading}>{loading?'Gerando…':'Gerar novamente'}</button><a className="btn btn-neutral" href="https://example.com" target="_blank" rel="noreferrer">Ler matéria original</a></div></article>}

export function HistoryPage(){return <div className="stack-lg"><div className="row-tight">{['Tudo','Importações','Financeiro','Conquistas'].map((x,i)=><button className="chip-toggle" aria-pressed={i===0} key={x}>{x}</button>)}</div><section className="card"><ol className="timeline list-plain">{[['bi-file-earmark-check','Hoje · 14:32','Extrato de agosto importado','42 transações adicionadas; quatro foram enviadas à triagem.'],['bi-check2-square','Hoje · 14:41','Conciliação concluída','Quatro decisões registradas preservando os valores originais.'],['bi-columns-gap','Ontem · 18:10','Aporte registrado','R$ 500,00 adicionados ao pilar Ativos internacionais.'],['bi-trophy','1 set · 09:20','Conquista desbloqueada','Meta Batida: objetivo concluído sem retirada antecipada.']].map(e=><li key={e[2]}><span className="timeline-line"/><span className="timeline-dot"><i className={`bi ${e[0]}`}/></span><p className="eyebrow">{e[1]}</p><h2 className="h-display">{e[2]}</h2><p className="small muted">{e[3]}</p><button className="btn btn-link">Ver detalhes</button></li>)}</ol></section></div>}

export function ProfilePage(){return <div className="stack-lg"><section className="card"><div className="row"><span className="avatar avatar-lg">MA</span><div><p className="eyebrow">Perfil local</p><h2 className="h-display">Marina Alencar</h2><p className="muted">Nível 3 · Estrategista ARCA</p></div></div><p className="small">2.840 de 3.500 XP</p><div className="bar bar-lg"><div className="bar-fill" style={{width:'81%'}}/></div></section><section className="grid grid-320"><article className="card"><p className="eyebrow">Missões</p>{['Revisar 4 lançamentos pendentes','Conferir a fatura Aurora','Importar o extrato da semana'].map((m,i)=><label className="pick" key={m}><input type="checkbox" defaultChecked={i===2}/><span>{m}</span></label>)}</article><article className="card"><p className="eyebrow">Conquistas</p>{['Escudo de Emergência','Equilíbrio Perfeito','Leitor de Mercado','Meta Batida'].map((b,i)=><div className="row-between" key={b}><span><i className={`bi ${i<2?'bi-award':'bi-lock'}`}/> {b}</span><span className="small muted">{i<2?'Obtida':'Bloqueada'}</span></div>)}</article></section><Link className="btn btn-primary" href="/perfil/privacidade">Dados, exportação e backup</Link></div>}

export function PrivacyPage(){const [backup,setBackup]=useState(false);return <div className="stack-lg"><section className="grid grid-320"><article className="card"><SectionTitle title="Banco de dados local"/><p className="metric">SQLite</p><p className="small muted">Seus dados financeiros permanecem neste dispositivo.</p><div className="row-tight"><button className="btn btn-neutral">Exportar JSON</button><button className="btn btn-neutral">Exportar CSV</button></div></article><article className="card"><SectionTitle title="Backup cifrado"/><span className="chip chip-warn"><i className="bi bi-cone-striped"/>Planejado</span><p className="small muted">A recuperação de chave ainda precisa ser definida e auditada. Nenhum backup foi enviado.</p><button className="btn btn-primary" disabled onClick={()=>setBackup(true)}>Fazer backup agora</button>{backup&&<p>Backup iniciado.</p>}</article></section><Notice icon="bi-shield-lock" title="Privacidade por princípio" text="A nuvem não recebe extratos, transações, saldos ou carteira em claro." tone="ok"/></div>}

export function SettingsPage(){const app=useApp();return <div className="grid grid-320"><section className="card"><SectionTitle title="Aparência"/><div role="group" className="segmented segmented-lg">{(['Claro','Escuro','Sistema'] as const).map(t=><button key={t} aria-pressed={app.theme===t} onClick={()=>app.setTheme(t)}>{t}</button>)}</div></section><section className="card"><SectionTitle title="Moeda, fuso e formato"/><label className="field">Moeda<select defaultValue="BRL"><option>BRL</option></select></label><label className="field">Fuso horário<select defaultValue="America/Sao_Paulo"><option>America/Sao_Paulo</option></select></label><label className="field">Idioma<select defaultValue="pt-BR"><option>Português (Brasil)</option></select></label></section><section className="card"><SectionTitle title="Estados para demonstração"/><div className="stack"><button className="btn btn-neutral" onClick={app.toggleOffline}>Alternar modo offline</button><button className="btn btn-neutral" onClick={app.toggleSurvival}>Alternar modo de sobrevivência</button><button className="btn btn-neutral" onClick={()=>app.open('onboarding')}>Reabrir onboarding</button></div></section><section className="card"><SectionTitle title="Sobre"/><p>Talentum · pré-alpha</p><p className="small muted">Piloto automático financeiro local-first e open-source.</p></section></div>}

export function OnboardingPage(){const app=useApp();return <section className="card card-lg"><p className="eyebrow">Primeiro acesso</p><h2 className="h-display-lg">Clareza para o presente. Disciplina para o futuro.</h2><div className="grid grid-230">{[['bi-file-earmark-arrow-up','Leitor automatizado','Importe PDF ou OFX sem digitação.'],['bi-flag','Metas','Veja quanto guardar por mês.'],['bi-columns-gap','Patrimônio','Acompanhe os quatro pilares.']].map(c=><article className="card" key={c[1]}><i className={`bi ${c[0]}`}/><h3>{c[1]}</h3><p className="small muted">{c[2]}</p></article>)}</div><Notice icon="bi-hdd" title="Seus valores ficam no computador" text="A nuvem cuida apenas da conta e do download; ela não conhece suas transações."/><button className="btn btn-primary" onClick={app.openImport}>Importar meu primeiro extrato</button></section>}

export function DetailPage({kind}:{kind:'card'|'goal'}){return kind==='card'?<div className="stack-lg"><CardsPage/><Link href="/extratos/cartoes" className="btn btn-neutral">Voltar aos cartões</Link></div>:<article className="card card-lg"><p className="eyebrow">Meta</p><h2 className="h-display-lg">Viagem em dezembro</h2><p className="metric num">72%</p><div className="bar bar-lg"><div className="bar-fill" style={{width:'72%'}}/></div><p>R$ 2.592,00 guardados de R$ 3.600,00.</p><Notice icon="bi-calendar-check" title="Plano viável" text="Mantenha R$ 300,00 por mês para concluir dentro do prazo." tone="ok"/><button className="btn btn-primary">Registrar contribuição</button></article>}
