'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { callApi, getJson, postJson, ApiError } from '@/lib/api-client';
import { formatCents } from '@/lib/format';

const message = (cause: unknown) => cause instanceof ApiError && cause.publicMessage ? cause.publicMessage : 'Não foi possível concluir a operação.';
const toCents = (value: string) => {
  const normalized = value.trim().replace(/\./g, '').replace(',', '.');
  const number = Number(normalized);
  if (!Number.isFinite(number) || number <= 0) return null;
  return Math.round(number * 100).toString();
};

export function CategoriesPage() {
  const [items, setItems] = useState<{id:string;name:string;kind:string}[]>([]), [name,setName]=useState(''), [kind,setKind]=useState('expense'), [error,setError]=useState(''), [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const x=await getJson<{categories:typeof items}>('/api/categories');setItems(x.categories);}catch(e){setError(message(e));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function create(event:FormEvent){event.preventDefault();try{await postJson('/api/categories',{name,kind});setName('');await load();}catch(e){setError(message(e));}}
  async function remove(id:string){try{await callApi('DELETE',`/api/categories/${id}`);await load();}catch(e){setError(message(e));}}
  return <div className="stack-lg"><form className="card card-lg" onSubmit={create}><h2 className="h-display">Nova categoria</h2>{error&&<p className="callout callout-danger" role="alert">{error}</p>}<div className="grid grid-260"><label className="field">Nome<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Tipo<select value={kind} onChange={e=>setKind(e.target.value)}><option value="expense">Despesa</option><option value="income">Receita</option><option value="transfer">Transferência própria</option></select></label></div><button className="btn btn-primary">Adicionar categoria</button></form><section className="card"><h2 className="h-display">Categorias</h2>{loading?<p className="muted">Carregando…</p>:items.length===0?<p className="muted">Nenhuma categoria cadastrada.</p>:<ul className="entity-list">{items.map(x=><li key={x.id}><span><strong>{x.name}</strong><small className="muted">{x.kind}</small></span><button className="btn btn-quiet" onClick={()=>remove(x.id)}>Excluir</button></li>)}</ul>}</section></div>;
}

type Obligation={id:string;description:string;amountCents:string;dueDate:string;status:string;recurrence:string;isEstimated:boolean};
export function ObligationsPage(){
  const [items,setItems]=useState<Obligation[]>([]),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[due,setDue]=useState(''),[recurrence,setRecurrence]=useState('none'),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const x=await getJson<{obligations:Obligation[]}>('/api/obligations');setItems(x.obligations);}catch(e){setError(message(e));}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
  async function create(event:FormEvent){event.preventDefault();const cents=toCents(amount);if(!cents){setError('Informe um valor maior que zero.');return;}try{await postJson('/api/obligations',{description,amountCents:cents,dueDate:new Date(`${due}T12:00:00`).toISOString(),status:'open',recurrence,isEstimated:false});setDescription('');setAmount('');setDue('');await load();}catch(e){setError(message(e));}}
  async function status(id:string,value:string){try{await callApi('PATCH',`/api/obligations/${id}`,{json:{status:value}});await load();}catch(e){setError(message(e));}}
  async function remove(id:string){try{await callApi('DELETE',`/api/obligations/${id}`);await load();}catch(e){setError(message(e));}}
  return <div className="stack-lg"><form className="card card-lg" onSubmit={create}><h2 className="h-display">Novo compromisso</h2>{error&&<p className="callout callout-danger" role="alert">{error}</p>}<div className="grid grid-260"><label className="field">Descrição<input required maxLength={100} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field">Valor<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label><label className="field">Vencimento<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="field">Recorrência<select value={recurrence} onChange={e=>setRecurrence(e.target.value)}><option value="none">Não recorrente</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label></div><button className="btn btn-primary">Salvar compromisso</button></form><section className="card"><h2 className="h-display">Compromissos</h2>{loading?<p className="muted">Carregando…</p>:items.length===0?<p className="muted">Nenhum compromisso cadastrado.</p>:<ul className="entity-list">{items.map(x=><li key={x.id}><span><strong>{x.description}</strong><small className="muted">R$ {formatCents(x.amountCents).value} · {new Date(x.dueDate).toLocaleDateString('pt-BR')}</small></span><span className="row-tight"><select aria-label={`Estado de ${x.description}`} value={x.status} onChange={e=>status(x.id,e.target.value)}><option value="open">Aberto</option><option value="paid">Pago</option><option value="cancelled">Cancelado</option></select><button className="btn btn-quiet" onClick={()=>remove(x.id)}>Excluir</button></span></li>)}</ul>}</section></div>;
}

type Income={id:string;description:string;amountCents:string;frequency:string;nextExpectedDate:string|null};
export function IncomesPage(){
  const [items,setItems]=useState<Income[]>([]),[description,setDescription]=useState(''),[amount,setAmount]=useState(''),[frequency,setFrequency]=useState('monthly'),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const x=await getJson<{incomes:Income[]}>('/api/incomes');setItems(x.incomes);}catch(e){setError(message(e));}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
  async function create(event:FormEvent){event.preventDefault();const cents=toCents(amount);if(!cents){setError('Informe um valor maior que zero.');return;}try{await postJson('/api/incomes',{description,amountCents:cents,frequency});setDescription('');setAmount('');await load();}catch(e){setError(message(e));}}
  return <div className="stack-lg"><form className="card card-lg" onSubmit={create}><h2 className="h-display">Nova fonte de renda</h2><p className="muted">Renda prevista não aumenta o Saldo Livre de Risco antes de entrar na conta.</p>{error&&<p className="callout callout-danger" role="alert">{error}</p>}<div className="grid grid-260"><label className="field">Descrição<input required maxLength={100} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field">Valor esperado<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Frequência<select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="monthly">Mensal</option><option value="biweekly">Quinzenal</option><option value="weekly">Semanal</option><option value="variable">Variável</option><option value="once">Uma vez</option></select></label></div><button className="btn btn-primary">Salvar fonte</button></form><section className="card"><h2 className="h-display">Fontes de renda</h2>{loading?<p className="muted">Carregando…</p>:items.length===0?<p className="muted">Nenhuma fonte de renda cadastrada.</p>:<ul className="entity-list">{items.map(x=><li key={x.id}><span><strong>{x.description}</strong><small className="muted">R$ {formatCents(x.amountCents).value} · {x.frequency}</small></span></li>)}</ul>}</section></div>;
}
