'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { callApi, getJson, ApiError } from '@/lib/api-client';
import { formatCents } from '@/lib/format';

type Transaction={id:string;occurredOn:string;description:string;amountCents:string;status:string;account:{id:string;name:string};category:{id:string;name:string;kind:string}|null;importBatchId:string|null};
type Revision={id:string;before:{description:string;categoryId:string|null;status:string};after:{description:string;categoryId:string|null;status:string};reason:string|null;createdAt:string};

export function TransactionDetail({transactionId}:{transactionId:string}){
  const [item,setItem]=useState<Transaction|null>(null),[categories,setCategories]=useState<{id:string;name:string}[]>([]),[history,setHistory]=useState<Revision[]>([]),[description,setDescription]=useState(''),[categoryId,setCategoryId]=useState(''),[status,setStatus]=useState('pending'),[reason,setReason]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [detail,cats,revisions]=await Promise.all([getJson<{transaction:Transaction}>(`/api/transactions/${transactionId}`),getJson<{categories:{id:string;name:string}[]}>('/api/categories'),getJson<{history:Revision[]}>(`/api/transactions/${transactionId}/history`)]);setItem(detail.transaction);setDescription(detail.transaction.description);setCategoryId(detail.transaction.category?.id??'');setStatus(detail.transaction.status);setCategories(cats.categories);setHistory(revisions.history);}catch(cause){setError(cause instanceof ApiError&&cause.publicMessage?cause.publicMessage:'Não foi possível consultar o lançamento.');}finally{setLoading(false);}},[transactionId]);
  useEffect(()=>{void load();},[load]);
  async function save(event:FormEvent){event.preventDefault();setError('');try{await callApi('PATCH',`/api/transactions/${transactionId}`,{json:{description,categoryId:categoryId||null,status,reason:reason||undefined}});setReason('');await load();}catch(cause){setError(cause instanceof ApiError&&cause.publicMessage?cause.publicMessage:'Não foi possível salvar a alteração.');}}
  if(loading)return <section className="card card-lg" aria-busy="true"><p className="muted">Carregando lançamento…</p></section>;
  if(!item)return <section className="card card-lg empty"><h2 className="h-display">Lançamento indisponível</h2><p className="muted">{error}</p><Link className="btn btn-neutral" href="/extratos">Voltar aos extratos</Link></section>;
  const money=formatCents(item.amountCents);
  return <div className="stack-lg"><form className="card card-lg" onSubmit={save}><p className="eyebrow">{new Date(item.occurredOn).toLocaleDateString('pt-BR')} · {item.account.name}</p><h2 className={money.negative?'h-display-lg figure-negative':'h-display-lg'}>{money.symbol} {money.value}</h2>{error&&<p className="callout callout-danger" role="alert">{error}</p>}<label className="field">Descrição<input required maxLength={300} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="grid grid-260"><label className="field">Categoria<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Sem categoria</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field">Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pendente</option><option value="posted">Confirmado</option></select></label></div><label className="field">Motivo da alteração<input maxLength={200} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Opcional"/></label><div className="row-tight"><button className="btn btn-primary">Salvar alteração</button><Link className="btn btn-neutral" href="/extratos">Voltar</Link></div></form><section className="card"><h2 className="h-display">Histórico de alterações</h2>{history.length===0?<p className="muted">Nenhuma edição manual registrada.</p>:<ol className="entity-list">{history.map(row=><li key={row.id}><span><strong>{new Date(row.createdAt).toLocaleString('pt-BR')}</strong><small className="muted">{row.reason??'Alteração manual'} · {row.before.description} → {row.after.description}</small></span></li>)}</ol>}</section></div>;
}
